### ISSUE TITLE
question

### ISSUE THREAD

**Issue by epinault** [jpmckinney/tf-idf-similarity#21]
so I am looking at this gem and is there a better way than just looping through the the corpus to verify which document are similar to which?

so say I have 10 documents I would need to go through each and through the rest to see how they compare.. so kind of n * (n-1).. so almost n2

is there a better way , say give me all the document matching a certain score mininum?

**Comment by benben** [comment]
this is how I am doing it right now, iterating over every document and calculate similarity to the corpus. would be interested in a solution too :raising_hand: :sparkling_heart:

**Comment by epinault** [comment]
@jpmckinney : any better idea ? Between I am having other issues with the gem installing it with bundler because of the native dependencies (might be a bug in bundler ) but for now I had to fork and remove the runtime dependencies since your code does not required  the unicode gem

**Comment by jpmckinney** [comment]
unicode_utils is needed to correctly split terms at word boundaries; the method used when unicode_utils is unavailable is okay, but not correct. What error do you get? Please create a new issue for that.

For your question, you want to know how similar each document is to a given document? I don't see how you can do that without actually calculating the similarity between that document and the others.

**Comment by epinault** [comment]
I am getting this https://github.com/bundler/bundler-features/issues/94#issuecomment-149331093

**Comment by epinault** [comment]
The problem is that I cannot install it at all due to some weird error (and cannot figure it out as no log gets  written). But once I remove the unicode gem it works. And I usually use bundler to install it rather than gem install (see my reference ticket). So I am tyring find a solution but I thought your gem looking at your code was doing similar thing and use tr instead of unicode.downcase? is there anything else I am missing?

**Comment by jpmckinney** [comment]
This is the important line: https://github.com/jpmckinney/tf-idf-similarity/blob/5c33eb46294d3776eb0d1917903ec9800ed96569/lib/tf-idf-similarity/document.rb#L79

I can bundle install without issue.

**Comment by jpmckinney** [comment]
It's been a while since there was activity, so closing this question issue, but please feel free to respond and I'll reopen.

**Comment by epinault** [comment]
I will try it again but I ended up forking it and removing UTF as in my case it did not matter as much. I will see if I still get that error again
